spring:
  server:
    port: 8188

  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/user_behaviour_analysis
          username: root
          password: 5323105
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml